#!/bin/zsh

export GPGKEY=BB1264F8

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
source /usr/share/virtualenvwrapper/virtualenvwrapper.sh

sshclean()
{
    rm ${HOME}/.ssh/tmp/*
}

source /home/bsaiz/Documents/Hosting/admin.dc1/password-store/bin/passswitch
source /home/bsaiz/.passswitch/lina.conf

alias ls='ls --color=auto'
alias l='ls -lF'
alias la='ls -laF'
alias emacs='emacs -nw'
alias e='emacs -nw'
alias v='vim'
alias src='source ~/.zshrc'
alias grep='grep --color=auto'
alias rmf='rm -f'
alias rmp='rm -P'
alias rmpf='rmf -P'
