# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
include:
- template: Security/Secret-Detection.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml

stages:
  - test
  - package
  - pages

sast:
  stage: test

package_vim:
  stage: package
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - tar -czf vim.tar.gz .vim .vimrc
  artifacts:
    paths:
      - vim.tar.gz

pages:
  stage: pages
  image:
    name: pandoc/core
    entrypoint: [""]
  script:
    - mkdir public
    - pandoc -s README.md -o public/index.html
  artifacts:
    paths:
      - public
