#!/bin/sh

set -e

battery=$(headsetcontrol -b 2>/dev/null | awk -F'Level:' '/Level/ {gsub(/[^0-9]/,"",$2); print $2; exit}')

if [[ -z "$battery" ]]; then
    exit 0
fi

if [ "$battery" -ge 100 ]; then
    echo ''
else
    echo "${battery}%"
fi
