#!/bin/bash

class=$(playerctl metadata --player=spotify --format '{{lc(status)}}')
icon=""

if [[ $class == "playing" ]]; then
  info=$(playerctl metadata --player=spotify --format '{{artist}} - {{title}}' | sed 's/\&/and/g')
  if [[ ${#info} -gt 40 ]]; then
    info=$(echo "$info" | cut -c1-40)"..."
  fi
  text=$info" "$icon
elif [[ $class == "paused" ]]; then
  text=$icon
elif [[ $class == "stopped" ]]; then
  text=""
fi

jq -nc --arg text "$text" --arg class "$class" '{text:$text,class:$class}'
