# Realtime scheduling module configuration.
# Configures PipeWire to run with high priority and real-time privileges if available.

context.modules = [
    { name = libpipewire-module-rt
        args = {
            nice.level   = -11
            rt.prio      = 88
        }
        flags = [ ifexists nofail ]
    }
]
