
# ▄▀█ █▀▄▀█ █▀▄
# █▀█ █░▀░█ █▄▀

# AMD GPU Optimizations for PadsTower

env = AMD_VULKAN_ICD,RADV
#env = VK_ICD_FILENAMES,/usr/share/vulkan/icd.d/radeon_icd.x86_64.json

#env = ENABLE_HDR_WSI,1
env = AQ_DRM_DEVICES,/dev/dri/card1

windowrule = workspace 1, match:class ^(gamescope|steam_app_).*$
windowrule = monitor desc:ASUSTek COMPUTER INC XG32WCS TALMAS012758, match:class ^(gamescope|steam_app_).*$
windowrule = immediate on, match:class ^(gamescope|steam_app).*$
windowrule = fullscreen on, match:class ^(gamescope|steam_app_).*$
