
# ▄▀█ █▀▄▀█ █▀▄
# █▀█ █░▀░█ █▄▀

# AMD GPU Optimizations for PadsTower

env = AMD_VULKAN_ICD,RADV
#env = VK_ICD_FILENAMES,/usr/share/vulkan/icd.d/radeon_icd.x86_64.json

#env = ENABLE_HDR_WSI,1
env = AQ_DRM_DEVICES,/dev/dri/card1

windowrule {
    name = steam-bigpicture
    match:class = ^(?i)(steam)$
    match:title = ^(?i)(Steam Big Picture Mode)$
    fullscreen = true
    monitor = desc:ASUSTek COMPUTER INC XG32WCS TALMAS012758
}

windowrule {
    name = steam-games
    match:class = ^(?i)(gamescope|steam_app_.*)$
    fullscreen = true
    monitor = desc:ASUSTek COMPUTER INC XG32WCS TALMAS012758
    immediate = true
}
