general {
    gaps_in = 4
    gaps_out = 5
    border_size = 1
    col.active_border = rgba(44464f77)
    col.inactive_border = rgba(1a1b2033)
    layout = dwindle
    resize_on_border = true
}

general:snap {
    enabled = true
    window_gap = 4 # pixels
    monitor_gap = 5 # pixels
}

group {
    col.border_active = rgba(44464f77)
    col.border_inactive = rgba(1a1b2033)
    col.border_locked_active = rgba(44464f77)
    col.border_locked_inactive = rgba(1a1b2033)
}
