# vim: set expandtab ts=4 sw=4:
#      ░▒▒▒░░░░░▓▓          ___________
#    ░░▒▒▒░░░░░▓▓        //___________/
#   ░░▒▒▒░░░░░▓▓     _   _ _    _ _____
#   ░░▒▒░░░░░▓▓▓▓▓▓ | | | | |  | |  __/
#    ░▒▒░░░░▓▓   ▓▓ | |_| | |_/ /| |___
#     ░▒▒░░▓▓   ▓▓   \__  |____/ |____/
#       ░▒▓▓   ▓▓  //____/

# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄

# See https://wiki.hyprland.org/Configuring/

source = ~/.config/hypr/conf/variables.conf
source = ~/.config/hypr/conf/monitor.conf
source = ~/.config/hypr/conf/environment.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/layout.conf
source = ~/.config/hypr/conf/misc.conf
source = ~/.config/hypr/conf/animations.conf
source = ~/.config/hypr/conf/keybindings.conf
source = ~/.config/hypr/conf/windowrules.conf

source = ~/.config/hypr/themes/common.conf # shared theme settings
source = ~/.config/hypr/themes/theme.conf # theme specific settings

source = ~/.config/hypr/monitors.conf # generated by nwg-displays
source = ~/.config/hypr/workspaces.conf # generated by nwg-displays

exec-once = ln -sf ~/.config/hypr/hosts/$(hostname).conf ~/.config/hypr/host-specific.conf
source = ~/.config/hypr/host-specific.conf
