
#  ██╗  ██╗██╗   ██╗██████╗ ██╗██████╗ ██╗     ███████╗
#  ██║  ██║╚██╗ ██╔╝██╔══██╗██║██╔══██╗██║     ██╔════╝
#  ███████║ ╚████╔╝ ██████╔╝██║██║  ██║██║     █████╗
#  ██╔══██║  ╚██╔╝  ██╔═══╝ ██║██║  ██║██║     ██╔══╝
#  ██║  ██║   ██║   ██║     ██║██████╔╝███████╗███████╗
#  ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝╚═════╝ ╚══════╝╚══════╝
#

general {
    lock_cmd = pidof hyprlock || hyprlock --immediate    # Commande de verrouillage officielle
    before_sleep_cmd = loginctl lock-session             # Verrouille AVANT la mise en veille
    after_sleep_cmd = hyprctl dispatch dpms on           # S'assure que l'écran s'allume au réveil
    ignore_dbus_inhibit = false
}

# Verrouillage (5 min)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Extinction écran (15 min)
listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on
}
