# vim: set expandtab ts=4 sw=4:

cursor {
    no_hardware_cursors = false
    enable_hyprcursor = true
}

# See https://wiki.hyprland.org/Configuring/Keywords/#executing

device {
    name = epic mouse V1
    sensitivity = -0.5
}

# See https://wiki.hyprland.org/Configuring/Variables/

gestures {
    #workspace_swipe = true
    #workspace_swipe_fingers = 3
    workspace_swipe_distance = 500
    workspace_swipe_invert = true
    workspace_swipe_min_speed_to_force = 30
    workspace_swipe_cancel_ratio = 0.5
    workspace_swipe_create_new = true
    workspace_swipe_forever = true
}

# █░░ ▄▀█ █▄█ █▀█ █░█ ▀█▀ █▀
# █▄▄ █▀█ ░█░ █▄█ █▄█ ░█░ ▄█

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/

dwindle {
    pseudotile = true
    preserve_split = true
    smart_split = false
    smart_resizing = true
    force_split = 0
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/

# master {
#     new_status = master
# }

# █▀▄▀█ █ █▀ █▀▀
# █░▀░█ █ ▄█ █▄▄

# See https://wiki.hyprland.org/Configuring/Variables/

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vfr = true
    vrr = 0
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    always_follow_on_dnd = true
    animate_manual_resizes = false
    force_default_wallpaper = 0
    on_focus_under_fullscreen = 2
}

render {
    direct_scanout = true
    # cm_auto_hdr = 2
    # cm_fs_passthrough = true
}

xwayland {
    force_zero_scaling = true
}


# █▀ █▀█ █░█ █▀█ █▀▀ █▀▀
# ▄█ █▄█ █▄█ █▀▄ █▄▄ ██▄

source = ~/.config/hypr/config/animations.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/decorations.conf
source = ~/.config/hypr/config/environment.conf
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/keybinds.conf
source = ~/.config/hypr/config/monitor.conf
source = ~/.config/hypr/monitors.conf

source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/themes/common.conf # shared theme settings
source = ~/.config/hypr/themes/theme.conf # theme specific settings
source = ~/.config/hypr/themes/colors.conf # wallbash color override
source = ~/.config/hypr/monitors.conf # initially empty, to be configured by user and remains static
source = ~/.config/hypr/workspaces.conf # initially empty, to be configured by user and remains static

exec-once = ln -sf ~/.config/hypr/hosts/$(hostname).conf ~/.config/hypr/host-specific.conf
source = ~/.config/hypr/host-specific.conf
