-- https://wiki.hypr.land/Configuring/Basics/Autostart/
hl.on("hyprland.start", function ()
  hl.exec_cmd("waybar")
  hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 || /usr/libexec/polkit-gnome-authentication-agent-1")
  hl.exec_cmd("exec-once = systemctl --user import-environment")
  hl.exec_cmd("exec-once = hash dbus-update-activation-environment 2>/dev/null")
  hl.exec_cmd("exec-once = dbus-update-activation-environment --systemd")
  hl.exec_cmd("exec-once = blueman-applet # systray app for Bluetooth")
  hl.exec_cmd("exec-once = /usr/bin/swayosd-server")
  hl.exec_cmd("exec-once = nm-applet --indicator # systray app for Network/Wifi")
  hl.exec_cmd("exec-once = wl-paste --type text --watch cliphist store # clipboard store text data")
  hl.exec_cmd("exec-once = wl-paste --type image --watch cliphist store # clipboard store image data")
  hl.exec_cmd("exec-once = 1password --silent")
end)
