
# █ █▄░█ █▀█ █░█ ▀█▀
# █ █░▀█ █▀▀ █▄█ ░█░

# See https://wiki.hyprland.org/Configuring/Variables/

input {
    kb_layout = us
    kb_variant = intl
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    numlock_by_default = true

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
        tap-to-click = true
        disable_while_typing = true
        scroll_factor = 0.5
        tap-and-drag = true
        drag_lock = false
    }
}

cursor {
    no_hardware_cursors = false
    enable_hyprcursor = true
}

# See https://wiki.hyprland.org/Configuring/Keywords/#executing

device {
    name = epic mouse V1
    sensitivity = -0.5
}

# See https://wiki.hyprland.org/Configuring/Variables/

gestures {
    #workspace_swipe = true
    #workspace_swipe_fingers = 3
    workspace_swipe_distance = 500
    workspace_swipe_invert = true
    workspace_swipe_min_speed_to_force = 30
    workspace_swipe_cancel_ratio = 0.5
    workspace_swipe_create_new = true
    workspace_swipe_forever = true
}
