
# █░░ ▄▀█ █▄█ █▀█ █░█ ▀█▀ █▀
# █▄▄ █▀█ ░█░ █▄█ █▄█ ░█░ ▄█

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/

dwindle {
    pseudotile = true
    preserve_split = true
    smart_split = false
    smart_resizing = true
    force_split = 0
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/

# master {
#     new_status = master
# }
