
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄

# See https://wiki.hyprland.org/Configuring/Monitors/

# Default / fallback monitor config
#monitor = ,preferred,auto,auto

# HiDPI
monitor = , preferred, auto, 1
