
# █░█ ▄▀█ █▀█ █ ▄▀█ █▄▄ █░░ █▀▀ █▀
# ▀▄▀ █▀█ █▀▄ █ █▀█ █▄█ █▄▄ ██▄ ▄█

# Main modifier
$mainMod = Super # super / meta / windows key

# Applications
$term    = alacritty
$editor  = vscodium
$file    = nautilus
$browser = firefox
$menu    = wofi -s ~/.config/wofi/menu.css
