# https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#force-apps-to-use-wayland

--enable-features=UseOzonePlatform,WebRTCPipeWireCapturer
--ozone-platform=wayland
--enable-gpu-rasterization
--enable-zero-copy
--disable-gpu-sandbox
