# https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#force-apps-to-use-wayland
--enable-features=UseOzonePlatform
--ozone-platform=wayland
--disable-gpu-rasterization
--disable-gpu-compositing
--enable-zero-copy
--disable-gpu-sandbox
--disable-dev-shm-usage
--no-sandbox