# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki https://wiki.hyprland.org/Configuring/Variables/#input

input {
    kb_layout = us
    kb_variant = intl
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 2
    float_switch_override_focus = 2
    numlock_by_default = true

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
        tap-to-click = true
        disable_while_typing = true
        scroll_factor = 0.5
        tap-and-drag = true
        drag_lock = false
    }
}